### ISSUE TITLE
stderr: /etc/openntpd/ntpd.conf: Permission denied

### ISSUE THREAD

**Issue by simb** [debops/ansible-ntp#10]
When I try to do the basic install using debops I am getting failures installing the openntp stuff.

TASK: [debops.ntp | Install OpenNTPd package] ********************************* 
failed: [web2] => {"failed": true}
stderr: /etc/openntpd/ntpd.conf: Permission denied
invoke-rc.d: initscript openntpd, action "start" failed.
dpkg: error processing package openntpd (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 openntpd
E: Sub-process /usr/bin/dpkg returned an error code (1)

After doing some google work I found this article https://bugs.launchpad.net/ubuntu/+source/openntpd/+bug/458061.  Comment 24  had a solution. https://bugs.launchpad.net/ubuntu/+source/openntpd/+bug/458061/comments/24  Going through these steps does allow my debops scripts to keep running on the affected server.

I don't think think this should require manual intervention but I am new to ansible and debops so I dont know how to actually fix it correctly.

Any ideas?

**Comment by drybjed** [comment]
@simb I've added a task to remove `ntp` if `openntpd` is installed, could you check if that helps with the Ubuntu issue?

**Comment by simb** [comment]
@drybjed I updated debops and saw your commit listed in the updates.  I created a new server and ran the script again.  It still failed. here is the output message.  Maybe that will help. I am not specifically setting any variables. Just trying to get the first run out of the way.

TASK: [debops.ntp | Install OpenNTPd package] ********************************* 
failed: [web2] => {"failed": true}
stderr: /etc/openntpd/ntpd.conf: Permission denied
invoke-rc.d: initscript openntpd, action "start" failed.
dpkg: error processing package openntpd (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 openntpd
E: Sub-process /usr/bin/dpkg returned an error code (1)

stdout: Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  libopts25
Use 'apt-get autoremove' to remove it.
The following NEW packages will be installed:
  openntpd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 33.9 kB of archives.
After this operation, 184 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe openntpd amd64 20080406p-7 [33.9 kB]
Fetched 33.9 kB in 0s (55.4 kB/s)
Selecting previously unselected package openntpd.
(Reading database ... 82856 files and directories currently installed.)
Preparing to unpack .../openntpd_20080406p-7_amd64.deb ...
Unpacking openntpd (20080406p-7) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up openntpd (20080406p-7) ...
Starting openntpd: Processing triggers for ureadahead (0.100.0-16) ...

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'openntpd' --no-install-recommends' failed: /etc/openntpd/ntpd.conf: Permission denied
invoke-rc.d: initscript openntpd, action "start" failed.
dpkg: error processing package openntpd (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 openntpd
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by drybjed** [comment]
@simb Currently `debops.ntp` defaults to OpenNTPD since it's lightweight and secure. I could perhaps add a few tasks that detect if host has already installed `ntpd` and switch to that, but I would like to check if that will make `debops.ntp` usable first. Could you set in your inventory:

    ntp_daemon: 'ntpd'

for these hosts, and then run DebOps on them to see if it will work with `ntpd` set as default?

**Comment by pipitone** [comment]
Just a heads up that I have encountered this same error on a fresh install of ubuntu 12.04. Before I found this issue, I found [this bug report](https://bugs.launchpad.net/ubuntu/+source/openntpd/+bug/458061) and restarted `apparmor` and then was able to run `apt-get install -f` to continue the `openntpd` install.

**Comment by dcc6fvo** [comment]
/etc/init.d/apparmor restart  solved for me

**Comment by ypid** [comment]
Maybe [debops-contrib.apparmor](https://github.com/debops-contrib/ansible-apparmor) could be used to automate this?

**Comment by drybjed** [comment]
Most likely, yes, but I don't feel confident with adding AppArmor support to DebOps. I need to learn more about it, and check the role. Because `AppArmor would need to be messed with before `debops.ntp` is run, it will most likely go into the common playbook, and since it wants to modify GRUB configuration, that would probably pull `debops.grub` to the common playbook as well if we want to be consistent - or carefully modify `/etc/default/grub` so that `debops.grub` can take it over. So, lots of stuff to check and think about. :-)
